from enum import StrEnum

from pydantic import Field

from .artifacts import ArtifactRef
from .base import ContractModel


class ErrorCode(StrEnum):
    INPUT_INVALID = "INPUT_INVALID"
    SOURCE_INVALID = "SOURCE_INVALID"
    POLICY_DENIED = "POLICY_DENIED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    SOURCE_UNRESOLVED = "SOURCE_UNRESOLVED"
    OWNER_UNRESOLVED = "OWNER_UNRESOLVED"
    NO_DATA = "NO_DATA"
    INCOMPARABLE = "INCOMPARABLE"
    ANALYZER_FAILED = "ANALYZER_FAILED"
    MODEL_OUTPUT_INVALID = "MODEL_OUTPUT_INVALID"
    SANDBOX_FAILED = "SANDBOX_FAILED"
    STALE_OPPORTUNITY = "STALE_OPPORTUNITY"
    STALE_CASE = "STALE_CASE"
    ARTIFACT_MISMATCH = "ARTIFACT_MISMATCH"
    NO_ACTIONABLE_PROBLEM = "NO_ACTIONABLE_PROBLEM"
    NO_ELIGIBLE_STRATEGY = "NO_ELIGIBLE_STRATEGY"
    NO_SELECTABLE_STRATEGY = "NO_SELECTABLE_STRATEGY"
    SCOPE_VIOLATION = "SCOPE_VIOLATION"
    GUARDRAIL_FAILED = "GUARDRAIL_FAILED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class NodeError(ContractModel):
    node_id: str = Field(min_length=1)
    code: ErrorCode
    message: str = Field(min_length=1, max_length=1000)
    retryable: bool
    attempt: int = Field(ge=1)
    diagnostic_ref: ArtifactRef | None = None
